# partly autogenerated, that's why it's so ugly!

# say 'make V=1' to see the full build output
ifndef V
Q = @
Q_LATEX = sh -c 'echo -e "   " `echo $$(basename "$$0") | tr a-z A-Z`"\t$${!\#/..\/..\//}"; ! "$$0" "$$@" | grep -A5 -E "^[^ ]+:[0-9]+:"'
Q_OTHER = sh -c 'echo -e "   " `echo $$(basename "$$0") | tr a-z A-Z`"\t$${!\#/..\/..\//}"; "$$0" "$$@" >/dev/null'
endif

LATEX = latex
PDFLATEX = pdflatex
BIBTEX = bibtex
DVIPS = dvips
DVIPDF = dvipdf
PDFTOEPS = pdftops -eps
PDFTOPS = pdf2ps
EPSTOPDF = epstopdf
FIGTODEV = fig2dev
MPOST = mpost

.PHONY: all clean archive

all:  thesis

texfiles = $(wildcard *.tex)

.PHONY: thesis
thesis: thesis.pdf

thesis.pdf: $(texfiles)
	$(Q) latexmk --shell-escape -interaction=nonstopmode -file-line-error -pdf thesis.tex

clean:
	rm -f *.aux
	rm -f thesis.dvi thesis.idx thesis.ind thesis.ilg thesis.out thesis.toc thesis.pdf thesis.log

archive: thesis-template.zip

thesis-template.zip: *.tex Makefile ETHlogo.* refs.bib *.pdf plots/*.pgf plots/*.png
	mkdir -p thesis
	cp `git ls-files "*.tex" Makefile "ETHlogo.*" *.pdf refs.bib` thesis/
	mkdir -p thesis/plots
	cp plots/*.pgf thesis/plots/
	cp plots/*.png thesis/plots/
	perl -i -pe 's/\$$VERSION\$$/'"$$(git describe)/" thesis/*.tex
	rm -f thesis-template.zip
	zip -r thesis-template.zip thesis/
	rm -rf thesis/
